[1]
title = "How to play Line Rider Python"
content = """Draw a line from the top left to the bottom \
    right with the left mouse button. Press the space bar to play and watch the \
    rider go. Press space again to stop and go back to editing. (paraphrased from \
    the original version of Line Rider)\n\
    That was interesting. Was it? If you want to do more, use the left and \
    right arrow keys to navigate the help contents to see how to do more.
    Note: If you open a menu and click on the dashed lines, you "tear off" \
    the menu to make a separate window for the menu.\n\
    Note2: \
    If you're on a mac, the menus are at the top of your screen, not this window."""
lines = []
lines_width = 1

[2]
title = "Editing tracks"
content = """Left mouse button: Draw/erase lines.\n\
    Middle mouse button: Zoom in and out of the track.\n\
    Right mouse button: Pan around the track.\n\
    In the Edit menu:\n\
    Undo and redo: Undoes and redoes your last action.\n\
    Toggle line snapping: Toggles the lines you draw to snap to the endpoints of \
    other lines.\n\
    In the Tools menu:\n\
    Pencil: For free-hand drawing\n\
    Line: Draws straight lines\n\
    Eraser: Removes lines from the track"""
lines = []
lines_width = 1

[3]
title = "Types of lines"
content = """Solid line: An ordinary line. However, unlike \
    the lines in the original Line Rider, the rider collides with BOTH SIDES of \
    the line.\n\
    Acceleration line: A solid line that accelerates the rider in the direction of \
    the arrow.\n\
    Scenery line: The rider does not collide with this line.\n\
    Spring line: Not implemented yet.\n\
    Trigger line: Not implemented yet."""
lines = []
lines_width = 1

[4]
title = "Playing tracks"
content = """Play: Starts the track.\n\
    Stop: Stops the track. You can alternate between playing and stopping by \
    pressing just the space bar.\n\
    Pause: Pauses the track. You can alternate between playing and pausing by \
    pressing just the "p" button.\n\
    Step: Plays one frame of the track, for precise track making.\n\
    Reset position: resets the position of the rider to the start point.\n\
    Flag: Saves the current position and velocity of the rider. This causes "Play" \
    to start the track from this point, and "Reset position" to reset to this point.\n\
    Reset flag: Removes the flag.\n\
    Play from beginning: Plays the track from the beginning, ignoring the flag.\n\
    Slow-mo: Toggles playing the track in slow motion."""
lines = []
lines_width = 1

[5]
title = "View options"
content = """Velocity vector: Shows the vector describing \
    the rider's speed and direction of motion. Red is slow, blue is fast.\n\
    Points: Shows the endpoints of the lines in the track. The radius of the \
    circle cooresponds with the radius of line snapping.\n\
    Thin lines: Turns the width of lines to be as thin as possible, in case you \
    need precision.\n\
    Status: Shows/hides the information on the top-left corner of the window.
    Starting point: Moves the camera to the starting point\n\
    Last line: Moves the camera to the end of the last line drawn.\n\
    Follow rider: Toggles whether the camera is following the rider in playback.\n\
    Grid and collisions: Debugging stuff. Don't worry about it :|"""
lines = []
lines_width = 1

[6]
title = "Saving and loading"
content = """New track: Erases the current track.
    Save track: Saves the current track with a given name to /savedLines.
    Load track: Lets you load a track from /savedLines.
    /SavedLines is a folder in the same place as where this .py file is.\n\
    When you exit, the current track is automatically saved to a file called \
    "ONEXITSAVE_".\n\
    When you open this program again, it automatically loads "ONEXITSAVE_"."""
lines = []
lines_width = 1

[7]
title = "Tips on making tracks"
content = """If you didn't already find out, the rider \
    will fall off his sled if you hit him hard enough. However, he'll also fall \
    off if a line forces him off the seat of his sled. Yes, he will fall off if a \
    line touches his butt. HE'S VERY SENSITIVE THERE :|\n\
    If, for whatever reason, you want to drive \
    the rider into a sharp angle, that will cause this program to lag (not crash). \
    If you really want to do it, I advise you to add in a small perpendicular line \
    at the point of intersection."""
lines = [
    [[174.0, 275.0], [491.0, 317.0]], [[491.0, 317.0], [188.0, 369.0]], [[480.0, 300.0], [480.0, 340.0]],
    [[43.0, 324.0], [169.0, 328.0]], [[169.0, 328.0], [133.0, 311.0]], [[169.0, 328.0], [134.0, 351.0]]
]
lines_width = 3

[8]
title = "Tips on making tracks"
content = """If you notice you're spending a lot of time \
    on a single track, it would be a good idea to make back up files just in case \
    something bad happens (eg this program somehow corrupts the save or you mess \
    up the track and can't fix it)\n\
    On drawing smooth curves:\n\n\
    Lazy way                  Lazy but effective          Pro (takes time)
    \n\n\n\n\n\n\
    Don't forget to have fun! ~Conundrumer"""
lines = [
    [[220.0, 238.0], [230.0, 292.0]], [[219.0, 260.0], [247.0, 312.0]], [[230.0, 292.0], [270.0, 331.0]],
    [[247.0, 312.0], [297.0, 343.0]], [[270.0, 331.0], [335.0, 352.0]], [[297.0, 343.0], [370.0, 354.0]],
    [[432.0, 239.0], [435.0, 260.0]], [[435.0, 260.0], [443.0, 283.0]], [[443.0, 283.0], [456.0, 304.0]],
    [[456.0, 304.0], [475.0, 324.0]], [[475.0, 324.0], [497.0, 337.0]], [[497.0, 337.0], [526.0, 346.0]],
    [[526.0, 346.0], [554.0, 350.0]], [[554.0, 350.0], [585.0, 351.0]], [[16.0, 230.0], [19.0, 346.0]],
    [[19.0, 346.0], [163.0, 347.0]], [[16.0, 230.0], [34.0, 346.0]], [[18.0, 260.0], [56.0, 347.0]],
    [[18.0, 278.0], [76.0, 346.0]], [[20.0, 297.0], [98.0, 346.0]], [[20.0, 314.0], [123.0, 348.0]],
    [[21.0, 329.0], [147.0, 346.0]]
]
lines_width = 1
